name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Java (for local act runner)
        if: env.ACT
        run: |
          apt-get update
          apt-get install -y openjdk-21-jdk
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./gradlew build

      - name: Rename JAR with Commit SHA
        id: rename
        run: |
          VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')
          SHA=$(git rev-parse --short HEAD)
          ORIG_JAR="build/libs/meteor-client-${VERSION}-local.jar"
          NEW_JAR="build/libs/meteor-client-${VERSION}-${SHA}.jar"
          mv "$ORIG_JAR" "$NEW_JAR"
          echo "renamed_jar=$NEW_JAR" >> $GITHUB_OUTPUT

      - name: Upload Renamed JAR
        uses: actions/upload-artifact@v4
        with:
          name: meteor-client-jar-${{ steps.rename.outputs.renamed_jar }}
          path: ${{ steps.rename.outputs.renamed_jar }}