name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: fuck permissions
        if: env.ACT
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Rename JAR
        id: rename
        run: |
          VERSION=$(./gradlew properties | grep "^minecraft_version:" | awk '{print $2}')
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          NEW_JAR="build/libs/meteor-client-${VERSION}-${SHA}.jar"
          mv "build/libs/meteor-client-${VERSION}-local.jar" "$NEW_JAR"
          echo "renamed_jar=$NEW_JAR" >> $GITHUB_OUTPUT

      - name: Get JAR SHA256
        run: sha256sum "${{ steps.rename.outputs.renamed_jar }}" | awk '{ print "SHA256:", $1 }'

      - name: Upload JAR
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: meteor-client-${{ steps.rename.outputs.version }}-${{ github.sha }}
          path: ${{ steps.rename.outputs.renamed_jar }}